name: camomile
chanels:
  - conda-forge
  - anaconda
dependencies:
  - python == 3.8.0
  - numpy
  - tqdm
  - nltk
  - jupyter
  - beautifulsoup4
  - urllib3
  - pip:
    - black
    - requests
    - pathlib
